Module2 task1
htmlacademy-react/1984913-what-to-watch-12 pull request #3
Opened 2023-03-05 16:36 UTC by sherrasy

2023-03-06 10:10 UTC, AlexMasterov requested changes
Для этого задания нужно немного доработать.

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/constants.ts
> +export {AllGenres, FILMS_AMOUNT, DEFAULT_GENRE, RATING_MAX, SignInErrors, FilmTabs};
AllGenre`s`
SignInError`s`
FilmTab`s`

Б9
> Перечисления названы существительными в единственном числе

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/components/film-review-card/film-review-card.tsx
> +      <div className="review__rating">{rating}</div>
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/223062566-e7ea75c2-dc70-4354-b89d-242ffc6947a1.png)

</details>

<details>
<summary>Ожидание (markup/movie-page-reviews.html)</summary>

![image](https://user-images.githubusercontent.com/700213/223062455-2a114be9-faf4-454f-8481-0ac63a364218.png)

</details>

Форматирование рейтинга отличается от примера в макете.

См. ТЗ:
> Оценка. Например, `8.9` (всегда один знак <ins>после запятой</ins>)

🤔

Можно оставить на усмотрение случайного проверяющего.

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/components/film-review-card/film-review-card.tsx
> +          <time className="review__date" dateTime={date.slice(0,10)}>{date.slice(0,10)}</time>
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/223063066-883c5413-fa81-4e68-94f6-06e6cab4ce55.png)

</details>

<details>
<summary>Ожидание (markup/movie-page-reviews.html)</summary>

![image](https://user-images.githubusercontent.com/700213/223062903-2577cc0f-9d93-41d1-8f39-c87021bcc212.png)

</details>

Форматирование даты отзыва отличается от примера в макете.

> Пока можно отложить

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/components/film-review-card/film-review-card.tsx
> +          <time className="review__date" dateTime={date.slice(0,10)}>{date.slice(0,10)}</time>
dateTime={`date.slice(0,10)`}

По спецификации значение атрибута `datetime` должно быть задано в формате [ISO 8601](https://ru.wikipedia.org/wiki/ISO_8601), который может иметь разную форму.

> См. подробней [Атрибут datetime](http://htmlbook.ru/html/time/datetime) и [Тег time, дата и время](https://htmlacademy.ru/courses/301/run/15)

https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/f541b227322cd24f21f9511f0bdaa05b8000e810/project/src/mocks/mock-reviews.ts#L4

Сейчас значение даты (`date`) имеет полную форму формата ISO и для атрибута `datetime` его можно использовать без обрезания.

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/components/film-review-card/film-review-card.tsx
> +          <time className="review__date" dateTime={date.slice(0,10)}>{date.slice(0,10)}</time>
2x `date.slice(0,10)`

Повторное создание массива и прочие вычисления повторяются во всем проекте.

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/components/film-details/film-details.tsx
> +              <Fragment key={star}>
<`Fragment` key={star}>

См. [React.Fragment](https://ru.reactjs.org/docs/react-api.html#reactfragment):
> Вы также можете использовать его сокращённый синтаксис `<></>`

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/constants.ts
> +const AllGenres = {
См. ТЗ:
> Список жанров строится на основании полученной с сервера информации о фильмах

Скорее всего подобное перечисление не потребуется.

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/components/app/app.tsx
<details>
<summary>project</summary>

https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/f541b227322cd24f21f9511f0bdaa05b8000e810/project/src/components/film-info/film-info.tsx#L2

https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/f541b227322cd24f21f9511f0bdaa05b8000e810/project/src/pages/film-page/film-page.tsx#L7
https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/f541b227322cd24f21f9511f0bdaa05b8000e810/project/src/pages/main-page/main-page.tsx#L6
https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/f541b227322cd24f21f9511f0bdaa05b8000e810/project/src/pages/my-list-page/my-list-page.tsx#L4
</details>

Сейчас все компоненты работают с тестовыми данными напрямую, а задание уже требует передавать их через пропсы react-компонентов.

См. внимательно задание:
> Теперь, используя props, добавим динамики в компоненты. Для этого в компоненте главной страницы приложения определите изменяемые данные — это будет название, жанр и дата выхода промо-фильма (того, что в шапке страницы). Получите их из props и вставьте в JSX компонента

> В файле index.tsx опишите данные, которые нужны в компоненте главной страницы приложения. <ins>Передайте их в компонент App</ins>

> В App получите эти данные из props и передайте их в компонент главной страницы приложения

Если хочешь, то это можно отложить до добавления роутера.

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/pages/my-list-page/my-list-page.tsx
> +  const filmsAmount = 9;
[Б7](https://up.htmlacademy.ru/react/12/criteries#b7) 
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/f541b227322cd24f21f9511f0bdaa05b8000e810/project/src/pages/my-list-page/my-list-page.tsx#L20

Для "своего списка" в ТЗ нет ограничений на кол. фильмов.

2023-03-06 10:10 UTC, AlexMasterov commented on project/src/pages/film-page/film-page.tsx
> +          <FilmsList films={mockFilms.slice(0,4)}/>
mockFilms.slice(0, `4`)

[Д5](https://up.htmlacademy.ru/react/12/criteries#d5)
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа


См. ТЗ:
> Блок «More like this» показывает похожие фильмы. В блоке отображается до 4-х карточек схожих фильмов

2023-03-07 19:24 UTC, sherrasy commented on project/src/components/film-details/film-details.tsx
> +              <Fragment key={star}>
Не использовала из-за передачи ключа

2023-03-07 19:26 UTC, sherrasy commented on project/src/components/film-review-card/film-review-card.tsx
> +          <time className="review__date" dateTime={date.slice(0,10)}>{date.slice(0,10)}</time>
Убрала повтор с датой. Если правильно понимаю, что нужно доработать остальные slice, могу исправить в следующих заданиях

2023-03-07 19:49 UTC, AlexMasterov reviewed
Пожалуйста, мелкие замечания в остатке исправь при выполнении следующего задания.

2023-03-07 19:49 UTC, AlexMasterov commented on project/src/components/film-reviews/film-reviews.tsx
> +        {reviews.slice(3,6).map((review)=><FilmReviewCard review={review} key={review.id}/>)}
reviews.slice(0, `3`)
reviews.slice(`3`, `6`)

Если по итогу останется такое решение, то для этих числовых значений потребуется создать "константы".

Д5

2023-03-07 19:49 UTC, AlexMasterov commented on project/src/pages/main-page/main-page.tsx
> +  const genres = ['All genres'];
const genres = [`'All genres'`];

https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/053e0cfa5bb1c534e2dfe88bbfc216c67dd2352f/project/src/utils/constants.ts#L5

2023-03-07 19:49 UTC, AlexMasterov commented on project/src/pages/main-page/main-page.tsx
> +  films?.forEach((film)=> {
films`?`.forEach((film)=> {

Зачем нужна проверка, если:

https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/053e0cfa5bb1c534e2dfe88bbfc216c67dd2352f/project/src/pages/main-page/main-page.tsx#L8-L9

https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/053e0cfa5bb1c534e2dfe88bbfc216c67dd2352f/project/src/pages/main-page/main-page.tsx#L12

2023-03-07 19:49 UTC, AlexMasterov commented on project/src/pages/main-page/main-page.tsx
> +  films?.forEach((film)=> {
<details>
<summary>pages/main-page/main-page.tsx</summary>

https://github.com/htmlacademy-react/1984913-what-to-watch-12/blob/053e0cfa5bb1c534e2dfe88bbfc216c67dd2352f/project/src/pages/main-page/main-page.tsx#L13-L17
</details>

🤔

```js
const genres = [DEFAULT_GENRE, ...new Set(films.map(({ genre }) => genre))];
```

2023-03-07 19:49 UTC, AlexMasterov commented on project/src/pages/my-list-page/my-list-page.tsx
> +  const FILMS_LIST_AMOUNT = films.length;
const `FILMS_LIST_AMOUNT` = films.length;

[Б5](https://up.htmlacademy.ru/react/12/criteries#b5) 
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации `camelCase`

2023-03-07 19:49 UTC, AlexMasterov commented on project/src/utils/constants.ts
> +export {FormatPattern, FILMS_AMOUNT,EQUAL_FILMS_MAX, DEFAULT_GENRE, RATING_MAX, SignInError, FilmTab};
В таком (утилитарном) модуле, который экспортирует всё, допускается `export` по месту:

```js
export const FILMS_AMOUNT = 8;
```

2023-03-07 19:49 UTC, AlexMasterov commented on project/src/utils/utils.ts
> +  const pattern = runTime > 59 ? FormatPattern.RunTimeLong : FormatPattern.RunTimeShort;
`59`

Д5

2023-03-07 19:49 UTC, AlexMasterov commented on project/src/utils/utils.ts
> +const formatRunTime = (runTime:number)=>{
const format`RunTime` = (`runTime`:number)=>{

Обращаю внимание, что `RunTime` и `Runtime` — не одно и тоже.

2023-03-07 19:50 UTC, merged